refactor: version information for enterprise css and js
SPANDigital/presidium-layouts-base pull request #3
Opened 2024-11-14 07:50 UTC by Zalaras

## Description
- Use enterprise script and style from content builder
    - Have default fallback

## Issue
- [x] :clipboard: [PRSDM-6838](https://spandigital.atlassian.net/browse/PRSDM-6838)

## Screenshots

## PR Readiness Checks
- [x] Your PR title conforms to conventional commits `<type>: <jira-ticket-num><title>`, for example: `fix: PRSDM-123 issue with login` with a maximum of 100 characters
- [x] You have performed a self-review of your changes via the GitHub UI
- [x] Comments were added to new code that can not explain itself (see [reference 1](https://bpoplauschi.github.io/2021/01/20/Clean-Code-Comments-by-Uncle-Bob-part-2.html) and [reference 2](https://blog.cleancoder.com/uncle-bob/2017/02/23/NecessaryComments.html))
- [x] New code adheres to the following quality standards:
  - Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
  - Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
  - DRY ([see reference](https://java-design-patterns.com/principles/#keep-things-dry))
  - YAGNI ([see reference](https://java-design-patterns.com/principles/#yagni))
- [x] Changes were tested locally

2024-11-14 08:27 UTC, CharlRitterDev approved these changes

2024-11-15 08:02 UTC, SamShiels approved these changes

2024-11-15 09:50 UTC, DustinFischer requested changes
My primary concern here is that this may work for enterprise, but it still won't solve the problem for open-source Presidium.

I fear that relying on something in content builder in the theme is dangerous -- theme should be completely decoupled from content builder. Theme can look down but it can't look up (to content builder)...

This should be fixed before we merge this.
I highly recommend looking into Hugo [Fingerprints](https://gohugo.io/hugo-pipes/fingerprint/)...
AFAIK that's the conventional way ... Hugo is chock full of utils for CSS and JS

2024-11-15 14:32 UTC, Zalaras commented
@DustinFischer
Fingerprints wont work here because they are used for resources that are generated with the build such as the `presidium.css` file.

Decoupling would be a separate discussion that I'm sure we can have next week in parking lot especially since Gerrit is working on the re-architecture.

Right now in order to get enterprise features into a docsite that is in Presidium enterprise it requires the `presidium-enterprise.js` and `presidium-enterprise.css` files. These are served from the server as static files, they are not embedded in the build but we still need the script tags to get them (docsites are not wrapped in anyway). After the last deploy we discovered the cache for these has been set to 1 year and I need a way to break this hence tacking on the version to get the browser to make a new request essentially for the same resource.
I'm not adding any new functionality here just trying to break the cache the browser has. This is also a priority for Monday's deployment

2024-11-18 07:48 UTC, DustinFischer commented on layouts/_default/baseof.html
> +
@Zalaras What file do these link to if the the param is a spoofed filename?

2024-11-18 08:20 UTC, DustinFischer approved these changes

2024-11-18 08:29 UTC, merged