feat: https://spandigital.atlassian.net/browse/PRSDM-6799 - Added missing community standards
SPANDigital/presidium-layouts-base pull request #9
Opened 2024-12-04 11:01 UTC by SamShiels

## Description
feat: https://spandigital.atlassian.net/browse/PRSDM-6799 - Added missing community standards

## Issue
- [ ] :clipboard: [JIRA_TICKET_URL](https://spandigital.atlassian.net/browse/PRSDM-6799)

## Screenshots

## PR Readiness Checks
- [ ] Your PR title conforms to conventional commits `<type>: <jira-ticket-num><title>`, for example: `fix: PRSDM-123 issue with login` with a maximum of 100 characters
- [ ] You have performed a self-review of your changes via the GitHub UI
- [ ] Comments were added to new code that can not explain itself (see [reference 1](https://bpoplauschi.github.io/2021/01/20/Clean-Code-Comments-by-Uncle-Bob-part-2.html) and [reference 2](https://blog.cleancoder.com/uncle-bob/2017/02/23/NecessaryComments.html))
- [ ] New code adheres to the following quality standards:
  - Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
  - Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
  - DRY ([see reference](https://java-design-patterns.com/principles/#keep-things-dry))
  - YAGNI ([see reference](https://java-design-patterns.com/principles/#yagni))

2024-12-04 11:55 UTC, richardwooding requested changes

2024-12-04 11:55 UTC, richardwooding commented on SECURITY.md
> +| 0.1.x     | :white_check_mark: |
Are you referring to a real version here?

2024-12-05 08:22 UTC, Quantumplate commented on SECURITY.md
> +| 0.1.x     | :white_check_mark: |
No its just the placeholder

2024-12-05 08:22 UTC, Quantumplate approved these changes
LGTM

2024-12-10 08:44 UTC, richardwooding approved these changes

2024-12-10 09:29 UTC, merged